export declare const RootDir = "./";
export declare const SrcDir = "./src";
export declare const TsRoot = "./src";
export declare const DestDir = "./dist/";
export declare const BuildDir = "./build/";
export declare const BundleDir = "./bundle";
export declare const AngularComponentsHtmlFiles: string;
export declare const AngularComponentsLessFiles: string;
export declare const AngularHtmlCopyTask = "AngularHtml.Copy";
export declare const AngularComponentLessTask = "AngularComponentLess";
export declare const AngularComponentLessCopyTask = "AngularComponentLess.Copy";
export declare const concatTask = "concat";
export declare const UmdTask = "umd";
export declare const BuildCopy = "BuildCopy";
export declare const WatchTask = "watch";
export declare const CleanBuildFolderTask = "cleanBuildFolder";
export declare const BuildTaskName = "build";
export declare const DefaultTaskName = "default";
export declare const LessTaskName = "less";
export declare const WatchTaskName = "watch";
export declare const AngularHTMLCopyTaskName = "AngularComponentHTMLCopy";
export declare const AngularLessCopyTaskName = "AngularComponentLessCopy";
export declare const BrowserSyncTaskName = "browserSync";
export declare const WebServerTaskName = "webserver";
export declare const CssBuildTaskName = "cssBuild";
